version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8083:80" # Frontend available on localhost:8080
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Backend exposed internally on port 5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
